### ISSUE TITLE
Переехать на гитлаб

### ISSUE THREAD

**Issue by Ganzeroar** [Ganzeroar/lesgaft_telebot#36]
Когда звёзды сойдутся

**Comment by DmitryLavrov** [comment]
А зачем переезжать на Gitlab?

**Comment by Ganzeroar** [comment]
> А зачем переезжать на Gitlab?

Пишут, что с него гораздо проще и эффективнее настраивать автодеплой, тестинг и ещё какие-то процессы

**Comment by DmitryLavrov** [comment]
Оставь здесь ссылку, если встретишь информацию про это

**Comment by Ganzeroar** [comment]
> Оставь здесь ссылку, если встретишь информацию про это

https://habr.com/ru/company/softmart/blog/310502/
